#!/usr/bin/env bash

ALPINE_VERSION=3.7
AWS_CLI_VERSION=1.14.58
S3CMD_VERSION=2.0.1
EB_VERSION=3.12.4

VERSION=1.5.8

sed -i 's/\(alpine:\)[^ ]\+/\1'${ALPINE_VERSION}/ Dockerfile
sed -i 's/\(awscli==\)[^ ]\+/\1'${AWS_CLI_VERSION}/ Dockerfile
sed -i 's/\(s3cmd==\)[^ ]\+/\1'${S3CMD_VERSION}/ Dockerfile
sed -i 's/\(awsebcli==\)[^ ]\+/\1'${EB_VERSION}/ Dockerfile

sed -i 's/\(Current version: \)[^ ]\+/\1'${VERSION}/ README.md
sed -i 's/\(\[alpine[^ ]\+ \)[^ ]\+/\1'${ALPINE_VERSION}/ README.md
sed -i 's/\(\[aws-cli[^ ]\+ \)[^ ]\+/\1'${AWS_CLI_VERSION}/ README.md
sed -i 's/\(\[s3cmd[^ ]\+ \)[^ ]\+/\1'${S3CMD_VERSION}/ README.md
sed -i 's/\(\[awsebcli[^ ]\+ \)[^ ]\+/\1'${EB_VERSION}/ README.md

docker build --pull .
VERSION_MESSAGE="alpine $ALPINE_VERSION, awscli $AWS_CLI_VERSION, s3cmd $S3CMD_VERSION, awsebcli $EB_VERSION"
git tag -a $VERSION -m "$VERSION_MESSAGE"
git commit -am "Release version $VERSION.

$VERSION_MESSAGE"
git push
git push --tags
