on: push

jobs:
  create_pull_request_to_production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.8.0
        with:
          script: |
            console.log('hello')
