on:
  pull_request:
    branches:
      - staging
    types:
      - closed

jobs:
  create_pull_request_to_production:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - uses: actions/github-script@0.8.0
        with:
          script: |
            console.log('comment in branch')
            const staging_pull_request = context.payload.pull_request
            const response = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: staging_pull_request.title.replace(/deploy to staging/i, 'Deploy to Production'),
              head: context.ref,
              base: 'master',
              body: staging_pull_request.body
            })
            console.log('response', response)
            const production_pull_request = response.data
            console.log('production_pull_request', production_pull_request)
            github.pulls.createReviewRequest({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: production_pull_request.number,
              reviewers: ['custombitbot']
            }).then(({ data, headers, status }) => {
              console.log('data', data, 'headers', headers, 'status', status)
            });
            github.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: production_pull_request.number,
              assignees: staging_pull_request.assignees
            })
            console.log('finished')
