on: push

jobs:
  create_pull_request_to_production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.8.0
        with:
          script: |
            let response = await github.pulls.get({
              owner: 'easystorage',
              repo: 'aws-cli',
              pull_number: 37
            })
            const staging_pull_request = response.data
            response = await github.pulls.get({
              owner: 'easystorage',
              repo: 'aws-cli',
              pull_number: 38
            })
            const production_pull_request = response.data
            github.issues.addAssignees({
              owner: 'easystorage',
              repo: 'aws-cli',
              issue_number: production_pull_request.number,
              assignees: staging_pull_request.assignees.map((user) => { return user.login })
            }).then(({ data, headers, status }) => {
              console.log('Assignees', 'data', data, 'headers', headers, 'status', status)
            }).catch(({ resource, status, error }) => {
              console.log('The assignee is', error.message)
            })
