on:
  pull_request:
    branches:
      - staging
    types:
      - closed

jobs:
  create_pull_request_to_production:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - uses: actions/github-script@0.8.0
        with:
          script: |
            const staging_pull_request = context.payload.pull_request
            let production_pull_request = null
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: staging_pull_request.title.replace(/deploy to staging/i, 'Deploy to Production'),
              head: staging_pull_request.head.ref,
              base: 'master',
              body: staging_pull_request.body
            }).then(({ data, headers, status }) => {
              production_pull_request = data
              github.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: production_pull_request.number,
                assignees: staging_pull_request.assignees.map((user) => { return user.login })
              })
            }).catch((data) => {
              if (data.errors[0].message.startsWith('A pull request already exists')) {
                github.pulls.list({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  head: staging_pull_request.head.ref,
                  base: 'master',
                }).then(({ data, headers, status }) => {
                  console.log(data)
                  production_pull_request = data[0]
                  github.pulls.update({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: production_pull_request.number,
                    state: 'open',
                  })
                  github.issues.removeLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: production_pull_request.number,
                    name: 'In Progress'
                  }).catch((data) => {
                    console.log(data.errors)
                  })
                })
              }
            })
