on:
  pull_request:
    branches:
      - staging
    types:
      - closed

jobs:
  create_pull_request_to_production:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - uses: actions/github-script@0.8.0
        with:
          script: |
            console.log(context)
